# Prometheus Configuration for AIRISS MSA

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'airiss-monitor'
    environment: '${ENV}'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Rule files
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # AIRISS LLM Service
  - job_name: 'airiss-llm'
    static_configs:
      - targets: ['airiss-llm:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL (if enabled)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['172.17.0.1:9323']

  # Node Exporter (host metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']