apiVersion: v1
kind: Namespace
metadata:
  name: airiss-msa
---
apiVersion: v1
kind: Secret
metadata:
  name: airiss-secrets
  namespace: airiss-msa
type: Opaque
stringData:
  openai-api-key: ${OPENAI_API_KEY}
  secret-key: ${SECRET_KEY}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airiss-config
  namespace: airiss-msa
data:
  PORT: "8080"
  USE_DATABASE: "false"
  LOG_LEVEL: "INFO"
  ALLOWED_ORIGINS: "https://ehr.company.com"
  ENABLE_METRICS: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airiss-llm-service
  namespace: airiss-msa
  labels:
    app: airiss-llm
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airiss-llm
  template:
    metadata:
      labels:
        app: airiss-llm
        version: v1.0.0
    spec:
      containers:
      - name: airiss
        image: airiss-llm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: airiss-secrets
              key: openai-api-key
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: airiss-secrets
              key: secret-key
        envFrom:
        - configMapRef:
            name: airiss-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: airiss-service
  namespace: airiss-msa
  labels:
    app: airiss-llm
spec:
  type: ClusterIP
  selector:
    app: airiss-llm
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: airiss-hpa
  namespace: airiss-msa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airiss-llm-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80